language: java
jdk:
  - oraclejdk10
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
script:
  - mvn clean install -P dev
  - mvn clean verify -P IT
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - bash <(curl -s https://codecov.io/bash)